### PR TITLE
Remove the 300ms delay when searching

### PR DESCRIPTION
**Pull request by xob**
This might be a personal preference, but coming from Sublime Text 3, I got used to the instant search it provided. I also found that performance was not an issue.

### CODE REVIEW

**Comment by gangstead** [comment]
I'll try this locally for a little while and see how I feel.  I'd welcome anyone else's opinion on it as well.

**Comment by xob** [comment]
Actually, this PR should either be declined or worked on a bit more. I did something similar in Atom's find-and-replace plugin. See this PR: https://github.com/atom/find-and-replace/pull/721

Thanks to some help, I managed to make it a setting in the package, to switch between instant and non-instant searches. A similar approach should be used here too.

I sadly don't have the time to put in the effort right now. Maybe in a week or two.

**Comment by gangstead** [comment]
Looks good. Thanks.

**Comment by gangstead** [comment]
Published in `v5.1.0`

**Pull request merged**
